// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DIRECT_URL'),
  },
  experimental: {
    externalTables: true,
  },
  // Supabase owns the auth schema; Prisma must not drop or alter these tables.
  tables: {
    external: [
      'auth.audit_log_entries',
      'auth.flow_state',
      'auth.identities',
      'auth.mfa_amr_claims',
      'auth.mfa_challenges',
      'auth.mfa_factors',
      'auth.oauth_authorizations',
      'auth.oauth_consents',
      'auth.one_time_tokens',
      'auth.refresh_tokens',
      'auth.schema_migrations',
      'auth.sessions',
      'auth.sso_domains',
      'auth.sso_providers',
      'auth.users',
    ],
  },
});
